# -*- coding: utf-8 -*-
"""Pixelguard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_FfFXk5QS-O94-fdemb1eAkoQ-221H_P
"""

import torch
import torchvision
import pandas as pd
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

from google.colab import drive
import os

# Mount Google Drive
drive.mount('/content/drive')

# Correct dataset path
dataset_path = "/content/drive/MyDrive/Pixel_guard_dataset"

print("Dataset Found:", os.path.exists(dataset_path))
print("\nContents of Dataset Folder:")
print(os.listdir(dataset_path))

import random
import matplotlib.pyplot as plt
from PIL import Image
import os

plt.figure(figsize=(12, 8))

for i in range(6):
    img_name = random.choice(fake_images)
    img = Image.open(os.path.join(fake_path, img_name))

    plt.subplot(2, 3, i + 1)
    plt.imshow(img)
    plt.title(img_name[:15])
    plt.axis("off")

plt.tight_layout()
plt.show()

from torchvision import transforms
from torchvision.datasets import ImageFolder
from torch.utils.data import random_split, DataLoader

# ==========================
# Image Transformations
# ==========================

train_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

val_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

# ==========================
# Load Dataset
# ==========================

dataset = ImageFolder(
    root=dataset_path,
    transform=train_transform
)

print("Classes :", dataset.classes)
print("Class Mapping :", dataset.class_to_idx)
print("Total Images :", len(dataset))

# ==========================
# Train / Validation Split
# ==========================

train_size = int(0.8 * len(dataset))
val_size = len(dataset) - train_size

train_dataset, val_dataset = random_split(
    dataset,
    [train_size, val_size]
)

# Apply validation transform
val_dataset.dataset.transform = val_transform

# ==========================
# DataLoaders
# ==========================

train_loader = DataLoader(
    train_dataset,
    batch_size=32,
    shuffle=True,
    num_workers=2,
    pin_memory=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=32,
    shuffle=False,
    num_workers=2,
    pin_memory=True
)

print(f"\nTraining Images   : {len(train_dataset)}")
print(f"Validation Images : {len(val_dataset)}")
print(f"Training Batches  : {len(train_loader)}")
print(f"Validation Batches: {len(val_loader)}")

"""**IMAGE PREPROCESSING**

"""

#WE ARE GOING TO USE RESNET WHICH TAKES IMG INPUT AS 224*224
#AND AS OUR INPUT IS UNSTRUCURED SO NEED TO CONVERT ALL OF EM TO 224*224 DIM
from torchvision import transforms

train_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

print(train_transform)

"""**DATASET AND DATALOADER**"""

from torchvision.datasets import ImageFolder
from torch.utils.data import DataLoader, random_split

# Load dataset
dataset = ImageFolder(
    root=dataset_path,
    transform=train_transform
)

# Print class information
print("Classes:", dataset.classes)
print("Class to Index:", dataset.class_to_idx)
print("Total Images:", len(dataset))

# Split dataset (80% Train, 10% Validation, 10% Test)
train_size = int(0.8 * len(dataset))
val_size = int(0.1 * len(dataset))
test_size = len(dataset) - train_size - val_size

train_dataset, val_dataset, test_dataset = random_split(
    dataset,
    [train_size, val_size, test_size]
)

print("\nDataset Split")
print("Training Images :", len(train_dataset))
print("Validation Images :", len(val_dataset))
print("Testing Images :", len(test_dataset))

# Create DataLoaders
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=32, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

print("\n✅ DataLoaders Created Successfully!")

"""**Loadinng and training our RESNET model**"""

from torchvision.models import resnet18, ResNet18_Weights

# Load pretrained ResNet18
model = resnet18(weights=ResNet18_Weights.DEFAULT)

print(model)

import torch.nn as nn
import torch
model.fc = nn.Linear(512, 2)
print(model)

print(model.fc)

criterion=nn.CrossEntropyLoss()
learning_rate = 0.0001
epochs=10
optimizer=torch.optim.Adam(model.parameters(),lr=learning_rate)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

print(device)
import torch

print("Device :", device)
print("Model Device :", next(model.parameters()).device)
print("GPU Name :", torch.cuda.get_device_name(0))

# TRAINING LOOP

best_val_loss = float("inf")

for epoch in range(epochs):

    model.train()                      # Set model to training mode
    total_epoch_loss = 0

    for images, labels in train_loader:

        # Move data to GPU (or CPU if GPU isn't available)
        images = images.to(device)
        labels = labels.to(device)

        # Forward pass
        outputs = model(images)

        # Calculate loss
        loss = criterion(outputs, labels)

        # Clear old gradients
        optimizer.zero_grad()

        # Backpropagation
        loss.backward()

        # Update model weights
        optimizer.step()

        # Accumulate loss for this epoch
        total_epoch_loss += loss.item()

    # Average loss for the epoch
    avg_loss = total_epoch_loss / len(train_loader)

    print(f"Epoch [{epoch+1}/{epochs}] - Loss: {avg_loss:.4f}")

model.eval()

# ==========================
# VALIDATION LOOP
# ==========================

model.eval()   # Set model to evaluation mode

val_loss = 0
correct = 0
total = 0

with torch.no_grad():

    for images, labels in val_loader:

        # Move data to GPU
        images = images.to(device)
        labels = labels.to(device)

        # Forward pass
        outputs = model(images)

        # Calculate validation loss
        loss = criterion(outputs, labels)
        val_loss += loss.item()

        # Predicted class
        _, predicted = torch.max(outputs, 1)

        # Count correct predictions
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

# ==========================
# VALIDATION METRICS
# ==========================

avg_val_loss = val_loss / len(val_loader)
val_accuracy = (correct / total) * 100

print("=" * 40)
print(f"Validation Loss     : {avg_val_loss:.4f}")
print(f"Validation Accuracy : {val_accuracy:.2f}%")
print("=" * 40)

# ==========================
# SAVE BEST MODEL
# ==========================

if avg_val_loss < best_val_loss:

    best_val_loss = avg_val_loss

    torch.save(model.state_dict(), "pixelguard_best_model.pth")

    print("✅ Best model saved!")

else:

    print("No improvement. Model not saved.")

!pip install scikit-learn

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    ConfusionMatrixDisplay,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

model.eval()

all_labels = []
all_predictions = []

with torch.no_grad():

    for images, labels in val_loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        _, predicted = torch.max(outputs, 1)

        all_labels.extend(labels.cpu().numpy())
        all_predictions.extend(predicted.cpu().numpy())

# ==========================
# Metrics
# ==========================

accuracy = accuracy_score(all_labels, all_predictions)
precision = precision_score(all_labels, all_predictions)
recall = recall_score(all_labels, all_predictions)
f1 = f1_score(all_labels, all_predictions)

print("="*50)
print("MODEL PERFORMANCE")
print("="*50)

print(f"Accuracy  : {accuracy*100:.2f}%")
print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1 Score  : {f1:.4f}")

print("="*50)
print("Classification Report")
print("="*50)

print(classification_report(
    all_labels,
    all_predictions,
    target_names=["Fake","Real"]
))

cm = confusion_matrix(all_labels, all_predictions)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["Fake","Real"]
)

plt.figure(figsize=(6,6))
disp.plot(cmap="Blues")
plt.title("Confusion Matrix")
plt.show()

torch.save(model.state_dict(), "pixelguard_resnet18.pth")

print("Model saved successfully!")

from google.colab import files

files.download("pixelguard_resnet18.pth")

from torchvision.models import resnet18, ResNet18_Weights
import torch.nn as nn

model = resnet18(weights=ResNet18_Weights.DEFAULT)

model.fc = nn.Linear(512,2)

model.load_state_dict(torch.load("pixelguard_resnet18.pth"))

model.to(device)

model.eval()

print("Model Loaded Successfully")

torch.save(model.state_dict(), "pixelguard_best_model.pth")

print("✅ Model saved successfully!")

model.load_state_dict(torch.load("pixelguard_resnet18.pth"))
model.eval()

from PIL import Image
from torchvision import transforms
import torch
import matplotlib.pyplot as plt

prediction_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

def predict_image(image_path):

    image = Image.open(image_path).convert("RGB")

    plt.imshow(image)
    plt.axis("off")
    plt.show()

    image = prediction_transform(image)
    image = image.unsqueeze(0)
    image = image.to(device)

    with torch.no_grad():

        outputs = model(image)

        probabilities = torch.softmax(outputs, dim=1)

        confidence, prediction = torch.max(probabilities, 1)

    classes = ["Fake", "Real"]

    print("="*45)
    print("Prediction :", classes[prediction.item()])
    print(f"Confidence : {confidence.item()*100:.2f}%")
    print("="*45)

predict_image("/content/WIN_20260628_15_14_39_Pro.jpg")

